//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class AnestheticManagement
    {
        public string GADuration { get; set; }
        public Nullable<float> BloodPressure { get; set; }
        public Nullable<float> HeartRate { get; set; }
        public Nullable<float> BrainTemperature { get; set; }
        public Nullable<bool> RectalTemperature { get; set; }
        public Nullable<bool> BloodGasses { get; set; }
    }
}
