//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class AnestheticRegimen
    {
        public string Anesthetic { get; set; }
        public string Drug { get; set; }
        public Nullable<double> O2 { get; set; }
        public Nullable<double> NitrousOxide { get; set; }
        public Nullable<double> MedicalAir { get; set; }
        public Nullable<bool> Fasted { get; set; }
        public Nullable<bool> OralInturbation { get; set; }
        public Nullable<double> Heparin { get; set; }
        public string Atropine { get; set; }
    }
}
