//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class AsepticTechnique
    {
        public Nullable<bool> Autoclave { get; set; }
        public Nullable<bool> HotBead { get; set; }
        public Nullable<bool> Gloves { get; set; }
        public Nullable<bool> Masks { get; set; }
        public Nullable<bool> Scrubs { get; set; }
        public Nullable<bool> Shower { get; set; }
    }
}
