//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class BehaviouralOutcomes
    {
        public Nullable<System.TimeSpan> PostStrokePeriod { get; set; }
        public string NeurologicalDetails { get; set; }
        public string SensorTests { get; set; }
        public string OtherTests { get; set; }
    }
}
