//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class BrainAssays
    {
        public Nullable<bool> WesternBlot { get; set; }
        public Nullable<bool> mRNA { get; set; }
        public Nullable<bool> miRNA { get; set; }
        public Nullable<bool> ELISA { get; set; }
        public Nullable<bool> Biochemical { get; set; }
        public Nullable<bool> HPLC { get; set; }
    }
}
