//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class BrainProcessing
    {
        public Nullable<bool> PerfusionFix { get; set; }
        public string CryostatFresh { get; set; }
        public Nullable<bool> CryostatFixSucrose { get; set; }
        public Nullable<bool> ParaffinMicrotome { get; set; }
        public string Immunohistochemistry { get; set; }
    }
}
