//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class DrugAdministration
    {
        public string DrugRoute { get; set; }
        public Nullable<double> DeliveryDuration { get; set; }
        public Nullable<double> DeliveryNumber { get; set; }
    }
}
