//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class Housing
    {
        public Nullable<System.TimeSpan> AcclimatisationPeriod { get; set; }
        public string AcousticBackground { get; set; }
        public Nullable<bool> AdditionalSpeciesLab { get; set; }
        public Nullable<bool> AdditionalSpeciesBuilding { get; set; }
        public string BeddingMaterial { get; set; }
        public string CageDistributor { get; set; }
        public string CageType { get; set; }
        public Nullable<float> CageSize { get; set; }
        public Nullable<int> NumberOfCageChanges { get; set; }
        public Nullable<bool> EnrichmentBySpecies { get; set; }
        public string EnrichmentType { get; set; }
        public Nullable<bool> FilterTop { get; set; }
        public Nullable<bool> FloodDeprivation { get; set; }
        public string FloodDeprivationSchedule { get; set; }
        public string Floor { get; set; }
        public string Handling { get; set; }
        public Nullable<bool> HealthCheck { get; set; }
        public string HealthCheckFrequency { get; set; }
        public string LidDistributor { get; set; }
        public string LidType { get; set; }
        public string Lighting { get; set; }
        public Nullable<System.TimeSpan> LightingHours { get; set; }
        public Nullable<double> LightPhaseIntensity { get; set; }
        public Nullable<double> DarkPhaseIntensity { get; set; }
        public Nullable<bool> GroupHousing { get; set; }
        public Nullable<int> ExperimenterCount { get; set; }
        public Nullable<int> AnimalsPerRoom { get; set; }
        public Nullable<int> CagesPerRack { get; set; }
        public Nullable<int> RacksPerRoom { get; set; }
        public string OdorSources { get; set; }
        public string RackType { get; set; }
        public Nullable<double> RoomSize { get; set; }
        public Nullable<double> RoomTempRange { get; set; }
        public Nullable<bool> RoomTempRegulated { get; set; }
        public Nullable<double> RelHumidityRange { get; set; }
        public Nullable<bool> RelHumidityReg { get; set; }
        public Nullable<bool> PathogenFree { get; set; }
        public string Ventilation { get; set; }
        public string WaterRegimen { get; set; }
    }
}
