//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class InfarctMeasurement
    {
        public Nullable<bool> TTC { get; set; }
        public string Histology { get; set; }
        public Nullable<bool> MRI { get; set; }
        public Nullable<float> CoronalNumber { get; set; }
        public Nullable<bool> RostroCovered { get; set; }
        public Nullable<bool> SwellingCorrection { get; set; }
    }
}
