//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class InternalValidity
    {
        public string Randomisation { get; set; }
        public Nullable<bool> SurgeryConceal { get; set; }
        public Nullable<bool> HandlingConceal { get; set; }
        public string BlindedInfarct { get; set; }
        public string BlindedNBS { get; set; }
        public string BlindedOther { get; set; }
    }
}
