//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class InVivoAssays
    {
        public Nullable<bool> InVivoGlutamate { get; set; }
        public Nullable<bool> InVivoOxidative { get; set; }
        public Nullable<bool> InVivoVasculature { get; set; }
    }
}
