//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class InVitroModel
    {
        public Nullable<bool> CellsInCulture { get; set; }
        public Nullable<bool> OrganotypicClices { get; set; }
        public Nullable<bool> HypoxicChamber { get; set; }
        public Nullable<bool> OxygenGlucoseDeprivation { get; set; }
        public Nullable<bool> GlutamateToxicity { get; set; }
    }
}
