//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class IschemiaModel
    {
        public string IschemiaType { get; set; }
        public string OcclusionMethod { get; set; }
        public Nullable<double> IschemiaDuration { get; set; }
        public string SecondaryInsult { get; set; }
    }
}
