//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class OcclusionResults
    {
        public Nullable<float> LDFDrop { get; set; }
        public Nullable<bool> BehaviouralScores { get; set; }
        public Nullable<bool> MRIData { get; set; }
    }
}
