//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class PostOpCarePack
    {
        public string SpecialDiet { get; set; }
        public Nullable<bool> SubCutFluids { get; set; }
        public string NumberCage { get; set; }
        public string Bedding { get; set; }
        public string LocalAnesthetics { get; set; }
        public string PainRelief { get; set; }
        public Nullable<bool> RecoveryQuestionnaire { get; set; }
        public Nullable<int> BodyWeightFrequency { get; set; }
    }
}
