//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study
    {
        public Study()
        {
            this.Outcomes = new HashSet<Outcome>();
            this.AnestheticRegimen = new AnestheticRegimen();
            this.AsepticTechnique = new AsepticTechnique();
            this.InternalValidity = new InternalValidity();
            this.OcclusionMonitoring = new OcclusionMonitoring();
            this.IschemiaModel = new IschemiaModel();
            this.DrugAdministraton = new DrugAdministration();
            this.InVivioAssays = new InVivoAssays();
            this.PostOpCarePack = new PostOpCarePack();
            this.InfarctMeasurement = new InfarctMeasurement();
            this.BehaviouralOutcomes = new BehaviouralOutcomes();
            this.BrainAssays = new BrainAssays();
            this.BrainProcessing = new BrainProcessing();
            this.InVitroModel = new InVitroModel();
            this.Housing = new Housing();
        }
    
        public int Id { get; set; }
        public string Strain { get; set; }
        public string Sex { get; set; }
        public string Source { get; set; }
        public string TerminationOptions { get; set; }
    
        public AnestheticRegimen AnestheticRegimen { get; set; }
        public AsepticTechnique AsepticTechnique { get; set; }
        public InternalValidity InternalValidity { get; set; }
        public OcclusionMonitoring OcclusionMonitoring { get; set; }
        public IschemiaModel IschemiaModel { get; set; }
        public DrugAdministration DrugAdministraton { get; set; }
        public InVivoAssays InVivioAssays { get; set; }
        public PostOpCarePack PostOpCarePack { get; set; }
        public InfarctMeasurement InfarctMeasurement { get; set; }
        public BehaviouralOutcomes BehaviouralOutcomes { get; set; }
        public BrainAssays BrainAssays { get; set; }
        public BrainProcessing BrainProcessing { get; set; }
        public InVitroModel InVitroModel { get; set; }
        public Housing Housing { get; set; }
    
        public virtual ICollection<Outcome> Outcomes { get; set; }
    }
}
