//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyClassLibrary
{
    using System;
    
    public partial class Termination
    {
        public Nullable<bool> SurvivedToEnd { get; set; }
        public Nullable<bool> DiedDuringSurgery { get; set; }
        public string PostOp { get; set; }
        public Nullable<bool> Autopsy { get; set; }
    }
}
